<h2 class="carrinho-vazio">Meu Carrinho</h2>

<div class="emptyCart" data-id="carrinhoVazio">
    <div class="wrp">
        <div class="innerCart">
          <em>Não há produtos em seu carrinho.</em>
	      <p>Para inserir algum produto no seu carrinho, navegue pelos departamentos ou utilize a busca do site. Ao encontrar os itens desejados, clique no botão COMPRAR localizado na página do produto.</p>
        </div>
	</div>
	<a href="http://www.mmstoree.com.br" class="bt btContinuar">Continuar Comprando</a>
</div>